### ISSUE TITLE
Customize and go through release checklist

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#96]
* [x] https://github.com/EmpathyApp/EmpathyApp/blob/master/docs/ways-of-working/release-checklist.md
* [x] User agreement to terms and conditions
* [x] Removing all extra themes
* [x] Upload *custom .htaccess* and test access (if all this has not been done before)
* [x] secure passwords
* [x] If needed: Remove and recreate database
* [x] ensure that stripe is in *live* mode
* [x] use separate build with different error handling
  * if possible: write to log instead of to screen
  * remove error reporting code
* [x] tagging and versioning
* [x] update to lastest version of EA plugin
* [x] restore skypenames: [skype skypenames="echo123, empathizer_p"] or probably new setup (ask Peijman)
